### ISSUE TITLE
Custom crafting recipes

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Looty#7]
We need to figure out how we want to register custom crafting recipes. It's quite straightforward to make a serializer for custom crafting recipes, it's moreso the question of where we should register them that's difficult.

### Recipes inside LootyTypes themselves

I'd rather not add a recipe component to items in Looty, since it essentially becomes a useless component after the type gets created. Instead, I think it might make sense to add a list of recipes as another parameter in `LootyType`, then register those once the type gets registered.

### Separate system for recipes

The system above should work quite nicely for our custom items, however, we may want to make recipes for new items without modifying their original config file (or in some cases we can't modify the item if it was created in someone else's plugin). Additionally, we may want recipes that craft to vanilla Minecraft items. 

This leads me to think we may want to have a separate folder where we can register a list of recipes, then read those upon startup. Maybe a dedicated `recipes` folder. We can then use #6 to use looty items as the inputs or results of our recipe. The way recipes work in vanilla, I believe we could add a custom recipe checker that specifically just reads the geary entity type of our items to verify whether the recipe should succeed. That way, if we ever make tweaks to our items (like lore) we dont need to worry about all the old items becoming useless.

**Comment by Derongan** [comment]
I prefer having recipes as entities that are loaded from config on startup.

This has some interesting side effects :)....

You can have an item that lets a player make their own recipe for example. You can even make recipe entities that expire after a certain number of ticks, or cause particles to be emitted when the recipe is completed... Or even add hitpoints as a crafting recipe requirement! (Only allow recipe complete if player health > x, then if player health is greater, damage them x on craft complete).

**Comment by Derongan** [comment]
Iirc the recipe API is kind of trash so we might have to dynamically manage shaped recipes in the system, but otherwise yea.

If you need the backlink to the items recipe (for example say we have enabled only craft known recipes, and want to allow players to reverse engineer some relic or something) that should be a different component we put on the item, not a requirement for an item to be craftable.

**Comment by 0ffz** [comment]
Closing this for now as a basic implementation of recipes now exists. If we want to discuss recipes that are themselves ECS entities in the future, make a separate issue.
