### ISSUE TITLE
Durability and consumable items

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Looty#8]
We want an action to be able to decrease durability or consume a relic outright.

Make a component for durability and make it have the option to either consume the relic entirely or put it in a broken state. We need to decide what being in a broken state actually does but for simplicity we could say it disables events and passive actions components.

**Comment by pixelfac** [comment]
Would the component track durability on the relic, like artificially adding durability to something like a torch or water bucket, or would it just fetch the durability of the item its attached to, like a pick or boots?

**Comment by 0ffz** [comment]
I can imagine us wanting to have durability on items without durability, but we'll always want to display it on the item itself somehow. I can imagine us using lore, different textures, or the actual item durability for this. Maybe we could have several display options stored in the component that you can pick between.

**Comment by 0ffz** [comment]
Closing issue for now until we figure out more specifically what we want. Recreate in Geary-addons when that is figured out.
